version: '3'

services:

    panomgr-db:
        container_name: panomgr-db
        image: mongo
        ports:
            - 27017
        networks:
            - panomgr-net
        volumes:
            - /mongo-db:/data/db

    panomgr-app:
        container_name: panomgr-app
        image: sgatade/panomgr-app
        networks:
            - panomgr-net
        volumes:
            - /home/centos/work/panomgr/gallery:/usr/src/panomgr/src/www/gallery
        ports:
            - 3003:3003

networks:
    panomgr-net: